### ISSUE TITLE
Nghiên cứu về github actions

### ISSUE THREAD

**Issue by quanduongduc** [quanduongduc/se2022-15.3#11]
Tài liệu anh Thành gửi về github actions : 

- [GitHub Actions Cheat Sheet](https://resources.github.com/whitepapers/github-actions-cheat/?fbclid=IwAR1PLAzai7XJiKhLlEyqymH3vJPSB1elpMqp4J2HKNrzyfsTUDJ0cVSPRp8)
- [Build and push Docker images](https://github.com/marketplace/actions/build-and-push-docker-images?fbclid=IwAR2ah4D8RGUDwwd6B0lxpEscDzQTjC4_7Zphd8NsZjokuB_7NmjlCm1ZmeI)
- [GitHub Actions Tutorial](https://www.youtube.com/watch?v=R8_veQiYBjI)

Các bạn xem nhá. Nếu có tài liệu bổ xung thì comment vô đây luôn nhé

**Comment by manhhus** [comment]
ok mình comfirm thông tin nhé

**Comment by nghianx121122** [comment]
ok nha để mình đọc

**Comment by nghianx121122** [comment]
@quanduongduc @manhhus ae ngâm cứu được nhiều chưa

**Comment by manhhus** [comment]
mình xem được cái youtube rồi
