### ISSUE TITLE
Lỗi workflow luôn thành công trong quá trình deploy

### ISSUE THREAD

**Issue by manhhus** [quanduongduc/se2022-15.3#15]
- tôi check thấy workflow luôn có trạng thái thành công dù quá trình deploy có thực sự thành công hay không
- - (workflow lỗi)[https://github.com/quanduongduc/se2022-15.3/actions/runs/3657167870/jobs/6180462020]
- Hình ảnh :
![image](https://user-images.githubusercontent.com/87703798/207371545-8c9ef8a6-c434-4005-96f5-2bd4563a0c12.png)

**Comment by nghianx121122** [comment]
Để mình check xem nó như thế nào nha

**Comment by quanduongduc** [comment]
Cái này có vẻ là lỗi bên phía ssh actions thử tìm ở [đây](https://github.com/appleboy/ssh-action) xem sao nhé

**Comment by quanduongduc** [comment]
Đã fix, check ở đây nhá #17
