### ISSUE TITLE
Triển Khai front-end

### ISSUE THREAD

**Issue by quanduongduc** [quanduongduc/se2022-15.3#19]
Thiết kế và triển khai frontend cho ứng dụng nghe nhạc (đã bàn luận chốt đề tài ở #8) :

- [x] #24
- [x] Triển khai UI
- [ ] Viết Test

Phần này code trên branch front-end nhé,  không push code lên branch main và các branch khác nhé

**Comment by nghianx121122** [comment]
ok nhé
