### ISSUE TITLE
Không kết nối được tới database khi sử dụng docker compose up trong môi trường deploy

### ISSUE THREAD

**Issue by quanduongduc** [quanduongduc/se2022-15.3#36]
![image](https://user-images.githubusercontent.com/59951771/216656267-becc842e-044b-431c-a93c-c49b1a03f6d2.png)

Có vẻ lỗi khi chạy docker compose, check kĩ file docker-compose.production ở branch deploy nhá

**Comment by quanduongduc** [comment]
@manhhus xử lí phần này nhá

**Comment by manhhus** [comment]
@quanduongduc ok để mai tôi check nhé
