### ISSUE TITLE
deploy to AWS

### ISSUE THREAD

**Issue by quanduongduc** [quanduongduc/se2022-15.3#5]
- Deploy to AWS EC2 server manually.
- Then try to create CD(continuous deployment) workflow using github action to : 
         - Build and push docker image to ECR.
         - Deploy code to AWS EC2.
         -  Workflow visualization (maybe change if needed) : 
<img width="1433" alt="Untitled" src="https://user-images.githubusercontent.com/59951771/203761708-46c0b067-a97b-4ed7-bae0-c9d30175c45d.png">

**Comment by manhhus** [comment]
Ok t đã bắt đầu nghiên cứu thực hiện các task

**Comment by nghianx121122** [comment]
Ok nha để t check kĩ quy trình của cái deploy này

**Comment by manhhus** [comment]
Mình cần thảo luận 1 chút, các bạn có thể họp vào sáng mai không

**Comment by quanduongduc** [comment]
> Mình cần thảo luận 1 chút, các bạn có thể họp vào sáng mai không

Chiều nay các bạn có rảnh không, phần này cần họp để thảo luận kĩ một chút

**Comment by nghianx121122** [comment]
> > Mình cần thảo luận 1 chút, các bạn có thể họp vào sáng mai không
> 
> Chiều nay các bạn có rảnh không, phần này cần họp để thảo luận kĩ một chút

ok chiều rảnh nha. Chiều họp

**Comment by manhhus** [comment]
vậy 2h mình bổ mít

**Comment by quanduongduc** [comment]
> vậy 2h mình bổ mít

oke nhá
