### ISSUE TITLE
Viết document cho project

### ISSUE THREAD

**Issue by quanduongduc** [quanduongduc/se2022-15.3#61]
Phần chỉ viết docs cho dự án, nên ko cần thiết kích hoạt các workflow sẽ được skip
Sử dụng commit như trong [đây](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs) nhá

**Comment by manhhus** [comment]
Ok nhé

**Comment by nghianx121122** [comment]
ok nha

**Comment by manhhus** [comment]
Usecase
![usecase-project drawio](https://user-images.githubusercontent.com/87703798/218251702-25c6439e-d8cd-4d40-a1b0-2c7f1890adfd.png)
