### ISSUE TITLE
Thống nhất đề tài web thực tế để triển khai

### ISSUE THREAD

**Issue by quanduongduc** [quanduongduc/se2022-15.3#8]
Bàn luận thống nhất đề tài web để triển khai ở đây nhé

**Comment by quanduongduc** [comment]
Hiện tại có hai chủ đề đang được đưa ra
- Web bán hàng
- Web nghe nhạc 

Mọi người còn ý tưởng gì nữa không ạ

**Comment by nghianx121122** [comment]
> Hiện tại có hai chủ đề đang được đưa ra
> 
> * Web bán hàng
> * Web nghe nhạc
> 
> Mọi người còn ý tưởng gì nữa không ạ

Mình nghĩ một trong 2 cái này là đủ rồi

**Comment by quanduongduc** [comment]
project của chúng ta chỉ cần demo một ứng dụng đơn giản nên web nghe nhạc thấy hợp lý hơn

**Comment by manhhus** [comment]
> 

Mình cũng vote web nghe nhạc nhé

**Comment by nghianx121122** [comment]
ok thế ae web âm nhạc
