### ISSUE TITLE
Bổ sung báo cáo tuần 1

### ISSUE THREAD

**Issue by manhhus** [quanduongduc/se2022-15.3#9]
- Bổ sung câu lệnh build image, câu lệnh run docker image, run docker compose
- Bổ sung mô tả các option khi build hoặc run như name, port...

**Comment by quanduongduc** [comment]
Sẽ bổ sung trong hôm nay nhé

**Comment by quanduongduc** [comment]
Check [ở đây](https://github.com/quanduongduc/se2022-15.3/pull/10) nhé
